[tool.poetry]
name = "pilot_log"
version = "0.1.0"
description = "Simple Django pilot log webapp"
authors = ["Yury V. Zaytsev <yury@shurup.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"

django = "*"
django-countries = "*"
django-bootstrap5 = "*"

python-dateutil = "*"
requests = "*"
playwright = "*"

[tool.poetry.dev-dependencies]
django-debug-toolbar = "*"

requests-mock = "*"

pytest-django = "*"
pytest-cov = "*"

ruff = "*"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"

[tool.coverage.run]
branch = true
source = ["."]
omit = ["**/tests/**", "**/test_*.py"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
