# Generated by Django 2.1.3 on 2018-11-04 16:51

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aerodrome",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=75)),
                ("city", models.CharField(max_length=75)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("icao_code", models.CharField(max_length=4)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("elevation", models.IntegerField()),
                ("priority", models.IntegerField()),
            ],
            options={
                "ordering": ("priority",),
            },
        ),
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("GLD", "Glider"), ("TMG", "Touring Motor Glider"), ("SEP", "Single Engine Piston")],
                        max_length=3,
                    ),
                ),
                ("maker", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=64)),
                ("registration", models.CharField(max_length=8, unique=True)),
            ],
            options={
                "ordering": ("registration",),
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("number", models.CharField(blank=True, max_length=255)),
                ("issue_date", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("authority", models.CharField(max_length=255)),
                ("remarks", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("departure_time", models.DateTimeField(unique=True)),
                ("arrival_time", models.DateTimeField(unique=True)),
                ("landings", models.PositiveSmallIntegerField(default=1)),
                (
                    "time_function",
                    models.CharField(
                        choices=[("PIC", "Pilot-in-Command"), ("DUAL", "Dual instruction time")],
                        max_length=5,
                    ),
                ),
                (
                    "launch_type",
                    models.CharField(
                        blank=True,
                        choices=[("SELF", "Self-launch"), ("WINCH", "Winch launch"), ("TOW", "Aerotow")],
                        max_length=5,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=255)),
                ("aircraft", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="logbook.Aircraft")),
            ],
            options={
                "verbose_name_plural": "Log entries",
                "ordering": ("-arrival_time",),
            },
        ),
        migrations.CreateModel(
            name="Pilot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=150)),
            ],
            options={
                "ordering": ("last_name",),
            },
        ),
        migrations.AlterUniqueTogether(
            name="pilot",
            unique_together={("first_name", "last_name")},
        ),
        migrations.AddField(
            model_name="logentry",
            name="copilot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="copilot_set",
                to="logbook.Pilot",
            ),
        ),
        migrations.AddField(
            model_name="logentry",
            name="from_aerodrome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="from_aerodrome_set",
                to="logbook.Aerodrome",
            ),
        ),
        migrations.AddField(
            model_name="logentry",
            name="pilot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pilot_set",
                to="logbook.Pilot",
            ),
        ),
        migrations.AddField(
            model_name="logentry",
            name="to_aerodrome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="to_aerodrome_set",
                to="logbook.Aerodrome",
            ),
        ),
    ]
