# Generated by Django 2.1.3 on 2018-11-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='icao_designator',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
