# Generated by Django 3.2.8 on 2021-10-10 12:12

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logbook", "0003_default_auto_field"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="logentry",
            constraint=models.CheckConstraint(
                check=models.Q(("arrival_time__gt", django.db.models.expressions.F("departure_time"))),
                name="arrival_after_departure",
            ),
        ),
    ]
