# Generated by Django 3.2.8 on 2021-10-10 12:21

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0004_logentry_arrival_after_departure"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="logentry",
            constraint=models.CheckConstraint(
                check=models.Q(("copilot", django.db.models.expressions.F("pilot")), _negated=True),
                name="copilot_not_pilot",
            ),
        ),
    ]
