# Generated by Django 3.2.9 on 2021-12-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logbook", "0005_logentry_copilot_not_pilot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraft",
            name="registration",
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
