# Generated by Django 4.0.2 on 2022-02-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0008_logentry_slots"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="logentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("time_function", "PIC"),
                    models.Q(models.Q(("time_function", "PIC"), _negated=True), ("cross_country", False)),
                    _connector="OR",
                ),
                name="no_pic_no_xc",
            ),
        ),
    ]
