# Generated by Django 4.2.5 on 2023-09-10 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0010_alter_certificate_options_logentry_night"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aircraft",
            options={"ordering": ("registration",), "verbose_name_plural": "aircraft"},
        ),
    ]
