# Generated by Django 4.2.5 on 2023-09-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0012_aircraft_currency_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="pilot",
            name="self",
            field=models.BooleanField(default=False),
        ),
    ]
