# Generated by Django 4.2.5 on 2023-09-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0013_pilot_self"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="relinquished",
            field=models.BooleanField(default=False),
        ),
    ]
