# Generated by Django 4.2.6 on 2023-10-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0014_certificate_relinquished"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="certificate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_until__gt", models.F("issue_date")),
                    _connector="OR",
                ),
                name="validity_after_issue",
            ),
        ),
    ]
