# Generated by Django 4.2.6 on 2023-11-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0015_certificate_validity_after_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="speed_unit",
            field=models.CharField(choices=[("KMH", "km/h"), ("KT", "kt"), ("MPH", "mph")], default="KT", max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aircraft",
            name="v_app",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Approach speed",
                null=True,
                verbose_name="Vapp",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="v_bg",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Best glide speed",
                null=True,
                verbose_name="Vbg",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="v_c",
            field=models.PositiveSmallIntegerField(blank=True, help_text="Cruise speed", null=True, verbose_name="Vc"),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="v_r",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Rotation speed",
                null=True,
                verbose_name="Vr",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="v_s",
            field=models.PositiveSmallIntegerField(blank=True, help_text="Stall speed", null=True, verbose_name="Vs"),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="v_y",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Best rate of climb speed",
                null=True,
                verbose_name="Vy",
            ),
        ),
    ]
