# Generated by Django 4.2.7 on 2023-11-01 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0016_aircraft_speed_unit_aircraft_v_app_aircraft_v_bg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supersedes_set",
                to="logbook.certificate",
            ),
        ),
    ]
