# Generated by Django 4.2.7 on 2023-11-01 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0017_certificate_supersedes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="relinquished",
        ),
    ]
