# Generated by Django 4.2.7 on 2023-11-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0018_remove_certificate_relinquished"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={
                "ordering": (
                    "name",
                    models.OrderBy(models.F("supersedes"), descending=True, nulls_last=True),
                    "-valid_until",
                ),
            },
        ),
    ]
