# Generated by Django 4.2.7 on 2023-11-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0019_alter_certificate_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="certificate",
            constraint=models.CheckConstraint(
                check=models.Q(("id", models.F("supersedes")), _negated=True),
                name="supersedes_self",
            ),
        ),
    ]
