# Generated by Django 4.2.7 on 2023-11-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0020_certificate_supersedes_self"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="certificate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("supersedes__isnull", False)),
                fields=("supersedes",),
                name="supersedes_unique",
            ),
        ),
    ]
