# Generated by Django 4.2.7 on 2023-11-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0021_certificate_supersedes_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="demonstrated_crosswind",
            field=models.PositiveSmallIntegerField(blank=True, help_text="Demonstrated crosswind in KT", null=True),
        ),
    ]
