# Generated by Django 4.2.7 on 2023-11-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0022_aircraft_demonstrated_crosswind"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="v_ref",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Uncorrected final approach speed",
                null=True,
                verbose_name="Vref",
            ),
        ),
    ]
