# Generated by Django 4.2.7 on 2023-11-04 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0023_aircraft_v_ref"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pilot",
            old_name="self",
            new_name="me",
        ),
    ]
