# Generated by Django 4.2.7 on 2023-11-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0024_rename_self_pilot_me"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pilot",
            constraint=models.UniqueConstraint(condition=models.Q(("me", True)), fields=("me",), name="only_one_me"),
        ),
    ]
