# Generated by Django 4.2.7 on 2023-11-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0026_alter_aerodrome_icao_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="remarks",
            field=models.TextField(blank=True),
        ),
    ]
