# Generated by Django 5.0.6 on 2024-05-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0028_aircraft_v_fe"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="night_vfr",
            field=models.BooleanField(default=False, help_text="Certified for Night VFR"),
        ),
    ]
