# Generated by Django 5.0.6 on 2024-05-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0029_aircraft_night_vfr"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="reduced_noise",
            field=models.BooleanField(default=False, help_text="Erhöhter Schallschutz"),
        ),
    ]
