# Generated by Django 5.0.6 on 2024-05-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0030_aircraft_reduced_noise"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64)),
                ("density", models.FloatField(help_text="Density in kg/L")),
            ],
        ),
        migrations.AddField(
            model_name="aircraft",
            name="fuel_types",
            field=models.ManyToManyField(to="logbook.fueltype"),
        ),
    ]
