# Generated by Django 5.1.7 on 2025-04-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0033_alter_aircraft_v_s"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aircraft",
            old_name="v_s",
            new_name="v_s1",
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="v_s1",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Stall speed (clean)", null=True, verbose_name="Vs1"
            ),
        ),
    ]
