# Generated by Django 5.2.1 on 2025-06-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0034_rename_aircraft_v_s_aircraft_v_s1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aircraft",
            old_name="v_bg",
            new_name="v_md",
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="v_md",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Vmd", help_text="Best glide speed"
            ),
        ),
    ]
