# Generated by Django 5.2.6 on 2025-12-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0035_rename_aircraft_v_bg_aircraft_v_md"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraft",
            name="v_s1",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Stall speed (flaps)", null=True, verbose_name="Vs1"
            ),
        ),
    ]
