# Generated by Django 5.2.6 on 2026-01-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logbook", "0036_alter_aircraft_v_s1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraft",
            name="v_s1",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Stall speed (clean)", null=True, verbose_name="Vs1"
            ),
        ),
    ]
